### ISSUE TITLE
Intergration Test of api failing 

### ISSUE THREAD

**Issue by Himanshu081** [vykes-mac/food-ordering-app#2]
i am facing this error:: Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'setString' was called on null.
Receiver: null
Tried calling: setString("CACHED_TOKEN", "dc7b6820f8f35f4011fa22118deb16c1"))

![image](https://user-images.githubusercontent.com/49179641/111056567-f338fa80-84a5-11eb-84c8-7863b2e7ecf0.png)

Flutter version:: 1.22.6
Dart version 2.10.5
Editor vscode

**Comment by Himanshu081** [comment]
![IMG_20210308_090356](https://user-images.githubusercontent.com/49179641/110271061-4960f600-7fed-11eb-966a-6767fadedc4b.jpg)
My code is completely same as written in original code still facing this issue. My test fails and redirects to this statement

**Comment by Himanshu081** [comment]
anyone plz help.....

**Comment by vykes-mac** [comment]
It seems you haven’t initialize the token store with an instance of sharedprefence. Look inside the CompositionRoot

**Comment by Himanshu081** [comment]
Yes,solved this. Now i am facing a problem in integrating onboarding screen with authpage ,but get error CubitConsumer called on null, can you give some idea how to integrate on boarding screen with your authpage code?
